const getFlagImageURL = (locationString: string) => {
  const countryCode = countryCodes[locationString]
  if (countryCode) {
    return `https://flagicons.lipis.dev/flags/4x3/${countryCode}.svg`
  }
  return null
}

const countryCodes = {
  'Los Angeles, CA': 'US',
  'Washington, D.C.': 'US',
  Amsterdam: 'NL',
  'Los Angeles': 'US',
  Washington: 'US',
  Samoa: 'WS',
  APAC: 'AP',
  EMEA: 'EM',
  AMERICAS: 'AM',
  EU: 'EU',
  Asia: 'AS',
  UK: 'GB',
  US: 'US',
  SA: 'SA',
  Oceania: 'OC',
  'South America': 'SA',
  Europe: 'EU',
  'North America': 'NA',
  Mexico: 'MX',
  'Amsterdam (AM)': 'NL',
  'Atlanta (AT)': 'US',
  'Chicago (CH)': 'US',
  'Dallas (DA)': 'US',
  'Dublin (DB)': 'IE',
  'Frankfurt (FR)': 'DE',
  'Helsinki (HE)': 'FI',
  'Hong Kong (HK)': 'HK',
  'London (LD)': 'GB',
  'Los Angeles (LA)': 'US',
  'Madrid (MD)': 'ES',
  'Manchester (MA)': 'GB',
  'Melbourne (ME)': 'AU',
  'Mexico City (MX)': 'MX',
  'Miami (MI)': 'US',
  'Milan (ML)': 'IT',
  'Montreal (MT)': 'CA',
  'Mumbai (MB)': 'IN',
  'New York (NY)': 'US',
  'Osaka (OS)': 'JP',
  'Paris (PA)': 'FR',
  'Seattle (SE)': 'US',
  'Seoul (SL)': 'KR',
  'Silicon Valley (SV)': 'US',
  'Singapore (SG)': 'SG',
  'Stockholm (SK)': 'SE',
  'Sydney (SY)': 'AU',
  'São Paulo (SP)': 'BR',
  'Tokyo (TY)': 'JP',
  'Toronto (TR)': 'CA',
  'Washington DC (DC)': 'US',
  Atlanta: 'US',
  Tampa: 'US',
  Dallas: 'US',
  Frankfurt: 'DE',
  'New York': 'US',
  London: 'GB',
  Lagos: 'NG',
  Sydney: 'AU',
  Chicago: 'US',
  Seattle: 'US',
  Milan: 'IT',
  Tokyo: 'JP',
  Madrid: 'ES',
  Singapore: 'SG',
  Mumbai: 'IN',
  Seoul: 'KR',
  Miami: 'US',
  'Colorado Springs': 'US',
  Ashburn: 'US',
  'New York (NJ)': 'US',
  Warsaw: 'PL',
  'Sao Paulo': 'BR',
  'Tel Aviv': 'IL',
  Bangalore: 'IN',
  'Delhi NCR': 'IN',
  'NOT AVAILABLE': 'XX',
  Austin: 'US',
  Belgrade: 'RS',
  Helsinki: 'FI',
  Phoenix: 'US',
  Global: 'global',
  ASIA: 'AS',
  APJ: 'AP',
  LATAM: 'SA',
  'Staten Island': 'US',
  Islamabad: 'PK',
  Dhaka: 'BD',
  Yangon: 'MM',
  Bangkok: 'TH',
  Hanoi: 'VN',
  'Ho Chi Minh City': 'VN',
  'Kuala Lumpur': 'MY',
  Jakarta: 'ID',
  Hongkong: 'HK',
  Taipei: 'TW',
  Manila: 'PH',
  Melbourne: 'AU',
  'Mexico City': 'MX',
  Bogotá: 'CO',
  Lima: 'PE',
  Fortaleza: 'BR',
  Santiago: 'CL',
  'Buenos Aires': 'AR',
  Stockholm: 'SE',
  Paris: 'FR',
  Zurich: 'CH',
  Marseille: 'FR',
  Lisbon: 'PT',
  Sofia: 'BG',
  Istanbul: 'TR',
  Moscow: 'RU',
  Cairo: 'EG',
  Jeddah: 'SA',
  Nairobi: 'KE',
  Johannesburg: 'ZA',
  Riyadh: 'SA',
  Doha: 'QA',
  Dubai: 'AE',
  'Fujairah City': 'AE',
  Karachi: 'PK',
  'San Jose': 'US',
  Montreal: 'CA',
  Toronto: 'CA',
  Chennai: 'IN',
  Osaka: 'JP',
  'Washington DC': 'US',
  Monreal: 'XX',
  Portland: 'US',
  Redding: 'US',
  'Salt Lake City': 'US',
  'San Francisco': 'US',
  'Santa Clara': 'US',
  'St. Luis': 'US',
  Vancouver: 'CA',
  Asuncion: 'PY',
  Bogota: 'CO',
  Cordoba: 'AR',
  'Guatemala City': 'GT',
  Montevideo: 'UY',
  'Panama City': 'PA',
  Quito: 'EC',
  'Rio de Janeiro': 'BR',
  'San-Jose': 'US',
  'Sao Paolo': 'BR',
  Athens: 'GR',
  Baku: 'AZ',
  Barcelona: 'ES',
  Bratislava: 'SK',
  Brussels: 'BE',
  Bucharest: 'RO',
  Budapest: 'HU',
  Chisinau: 'MD',
  Copenhagen: 'DK',
  Dublin: 'IE',
  Dusseldorf: 'DE',
  Edinburgh: 'GB',
  Florence: 'IT',
  Glasgow: 'GB',
  Kyiv: 'UA',
  Ljubljana: 'SI',
  Manchester: 'GB',
  Nicosia: 'CY',
  'Novi Travnik': 'BA',
  Oslo: 'NO',
  Palermo: 'IT',
  Porto: 'PT',
  Prague: 'CZ',
  Reykjavik: 'IS',
  Riga: 'LV',
  Rome: 'IT',
  Sevilla: 'ES',
  Tallinn: 'EE',
  Tirana: 'AL',
  Vienna: 'AT',
  Vilnius: 'LT',
  Zagreb: 'HR',
  'Hong Kong': 'HK',
  Nagano: 'JP',
  'New Delhi': 'IN',
  Pune: 'IN',
  'Cape Town': 'ZA',
  Casablanca: 'MA',
  Fez: 'MA',
  Tunis: 'TN',
  'EU-Nord-1EU-West-1US-Chicago-1SG-Singapore-1': 'XX',
  Frankurt: 'XX',
  Falkenstein: 'DE',
  Nuremberg: 'DE',
}
